version: '3.8'

# this docker file is based on this tutorial:
# https://www.dabbleofdevops.com/blog/setup-a-postgres-python-docker-dev-stack

services:

  postgres_db:
    image: postgres:11.1
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
      POSTGRES_USER: root
    ports:    # Set up ports exposed for other containers to connect to
      - 8432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_app:
    container_name: lab3-app
    build:
      context: .
      dockerfile: Dockerfile
    # Змонтувати локальний каталог lab3 до робочого каталогу в контейнері
    #    remove this section in release build 
    volumes:
      - ./lab3:/code  
    depends_on:
      - postgres_db
    command:
      tail -f /dev/null
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db
    depends_on:
      - postgres_db

