version: '3.8'

# this docker file is based on this tutorial:
# https://www.dabbleofdevops.com/blog/setup-a-postgres-python-docker-dev-stack

services:

  postgres_db:
    image: postgres:11.1
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
      POSTGRES_USER: root
    ports:    # Set up ports exposed for other containers to connect to
      - 8432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_app:
    container_name: lab3-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    command:
      tail -f /dev/null
      
  phppgadmin:
    image: "bitnami/phppgadmin:7.13.0"
    ports:
      - "8080:8080"
    #  - '443:8443'
    environment:
      DATABASE_HOST: postgres_db
    depends_on:
      - postgres_db
